spring.application.name=Recruit
spring.datasource.url=jdbc:mysql://localhost:3306/poo
spring.datasource.username=root
spring.datasource.password=


# update = creates tables if missing, updates columns if changed — NO data loss

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#server.port=8080
